### ISSUE TITLE
This mod is would be cool if it worked

### ISSUE THREAD

**Issue by Beez3-A** [K0LALA/SlimeMap#1]
Idk man this mod just does not work, I've tried it using jus this mod installed and it does not work. I dont see any slime chunks on the map, it just shows vanilla map.

I don't understand why it does not work 

Cool idea if it did, and if it did work would this be integrated into a mod like map atlases ect.

**Comment by K0LALA** [comment]
Hi, thanks for downloading and trying the mod. Which map did you use, the mod adds a slime map and is different from the normal map. If you are using the right map, test in a biome other than plains for example, since the slime chunks are represented using the same green as grass (I plan on adding a config for this). If all of this didn't work, you can provide more information like a screenshot and version of Minecraft/Fabric/Mod. Concerning the implementation, this is a great idea, I'm gonna look into that 👍

**Comment by Beez3-A** [comment]
Okay something weird is happening, 

It's working now, even in plains biome. IDK really weird lol. I'll come back if it stops working maybe in regards to another incompatible mod, but for now its working and that's great! 

Anyways cool mod man, also I saw your profile on Modrinth and your advanced locater mod. This mod is so useful haha I needed it! good work!

**Comment by K0LALA** [comment]
Happy it works now 👍, contact me back if needed. I'm glad you took a look at Advanced Locate as well.
